version: "3.3"
services:
  cult_app:
    container_name: cultural_board_backend
    image: cultural_board_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - cult_board_images:/usr/src/app/backend/images
    ports:
      - "3891:3001"
    env_file:
      - .env
    networks:
      - backend_welfare-board-strapi

volumes:
  cult_board_images:

networks:
  backend_welfare-board-strapi:
    external: true